/**
 * @rebasepro/sdk-generator
 *
 * Generates a purely typed Typescript database definition.
 */

import { EntityCollection } from "@rebasepro/types";
import { generateTypedefs } from "./generate-types";

export { generateTypedefs } from "./generate-types";
export { toPascalCase, toCamelCase, toSafeIdentifier, indent } from "./utils";

// ─── Public API ────────────────────────────────────────────────────

export interface GeneratedFile {
    /** Relative file path within the output directory */
    path: string;
    /** File content */
    content: string;
}

export interface GenerateSDKOptions {
    /** Whether to include a README file (default: true) */
    includeReadme?: boolean;
}

export function generateSDK(
    collections: EntityCollection[],
    options: GenerateSDKOptions = {},
): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    files.push({
        path: "database.types.ts",
        content: generateTypedefs(collections)
    });

    if (options.includeReadme !== false) {
        files.push({
            path: "README.md",
            content: `# Rebase SDK

> Auto-generated by \`rebase generate-sdk\`. Do not edit manually.

## Usage

1. Install the client package:
   \`\`\`bash
   npm install @rebasepro/client
   \`\`\`

2. Initialize with your generated types:
   \`\`\`typescript
   import { createRebaseClient } from '@rebasepro/client';
   import type { Database } from './database.types';

   const rebase = createRebaseClient<Database>({
       baseUrl: 'http://localhost:3001',
       // token: '...', // User token if not using auth module
   });

   // Both syntax styles are fully typed!
   const { data: users } = await rebase.data.users.find();
   const { data: posts } = await rebase.data.collection('posts').find();
   \`\`\`
`
        });
    }

    return files;
}
