// This file is auto-generated by `pnpm db:generate`.
// Do not edit manually.
//
// Run `pnpm db:generate` to regenerate this file from your collections.

export const tables = {};
export const enums = {};
export const relations = {};
