steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/firecms-backend/firecms-discord-bot:latest', '-f', 'discord-bot/Dockerfile', '.']
images:
- 'gcr.io/firecms-backend/firecms-discord-bot:latest'
