/**
 * @category Models
 */
export type ChipColor =
    | "blueLighter"
    | "cyanLighter"
    | "tealLighter"
    | "greenLighter"
    | "yellowLighter"
    | "orangeLighter"
    | "redLighter"
    | "pinkLighter"
    | "purpleLighter"
    | "grayLighter"

    | "blueLight"
    | "cyanLight"
    | "tealLight"
    | "greenLight"
    | "yellowLight"
    | "orangeLight"
    | "redLight"
    | "pinkLight"
    | "purpleLight"
    | "grayLight"

    | "blueDark"
    | "cyanDark"
    | "tealDark"
    | "greenDark"
    | "yellowDark"
    | "orangeDark"
    | "redDark"
    | "pinkDark"
    | "purpleDark"
    | "grayDark"

    | "blueDarker"
    | "cyanDarker"
    | "tealDarker"
    | "greenDarker"
    | "yellowDarker"
    | "orangeDarker"
    | "redDarker"
    | "pinkDarker"
    | "purpleDarker"
    | "grayDarker";
