

export interface RebaseCollectionsPluginOptions {
    /**
     * The path to the collections directory containing the schema definitions.
     * Use a relative or absolute path from the root of your frontend workspace.
     */
    collectionsDir: string;
}

/**
 * A Vite plugin that dynamically loads and automatically wires Rebase collections.
 * It provides a virtual module "virtual:rebase-collections" that statically exports the resolved collections array.
 */
export function rebaseCollectionsPlugin(options: RebaseCollectionsPluginOptions) {
    const virtualModuleId = 'virtual:rebase-collections';
    const resolvedVirtualModuleId = '\0' + virtualModuleId;

    return {
        name: 'rebase-collections-plugin',
        resolveId(id: string) {
            if (id === virtualModuleId) {
                return resolvedVirtualModuleId;
            }
            return null;
        },
        load(id: string) {
            if (id === resolvedVirtualModuleId) {
                // Vite evaluates `import.meta.glob` relative to the project root.
                // We ensure it starts with '/' so Vite knows evaluating it from the root.
                const globPath = options.collectionsDir.startsWith('/')
                    ? `${options.collectionsDir}/*.ts`
                    : `/${options.collectionsDir}/*.ts`;

                return `
                    // GENERATED BY @rebasepro/core Vite Plugin
                    const collectionModules = import.meta.glob('${globPath}', { eager: true });
                    console.log("[Rebase Glob Plugin] Loading from ${globPath}", collectionModules);
                    export const collections = Object.values(collectionModules)
                        .map((module) => module.default)
                        .filter(Boolean);
                `;
            }
            return null;
        }
    };
}
