// This file is auto-generated by the FireCMS Drizzle generator. Do not edit manually.

import { primaryKey, pgTable, integer, varchar, boolean, timestamp, jsonb, pgEnum, numeric, serial, pgPolicy } from 'drizzle-orm/pg-core';
import { relations as drizzleRelations, sql } from 'drizzle-orm';

export const postsStatus = pgEnum("posts_status", ['draft', 'review', 'published', 'archived']);

export const authors = pgTable("authors", {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    email: varchar("email").notNull(),
    picture: varchar("picture")
});

export const posts = pgTable("posts", {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    content: varchar("content"),
    status: postsStatus("status"),
    author_id: integer("author_id").references(() => authors.id, { onDelete: "set null" })
});

export const postsTags = pgTable("posts_tags", {
    post_id: integer("post_id").notNull().references(() => posts.id, { onDelete: "cascade" }),
    tag_id: integer("tag_id").notNull().references(() => tags.id, { onDelete: "cascade" }),
}, (table) => ({
    pk: primaryKey({ columns: [table.post_id, table.tag_id] })
}));

export const privateNotes = pgTable("private_notes", {
    id: serial("id").primaryKey(),
    title: varchar("title").notNull(),
    content: varchar("content"),
    user_id: varchar("user_id").notNull(),
    is_locked: boolean("is_locked")
}, (table) => ([
    pgPolicy("admin_bypass", { as: "permissive", for: "all", to: ["public"], using: sql`(true) AND (auth.roles() ~ 'admin')`, withCheck: sql`(true) AND (auth.roles() ~ 'admin')` }),
    pgPolicy("owner_access", { as: "permissive", for: "all", to: ["public"], using: sql`${table.user_id} = auth.uid()`, withCheck: sql`${table.user_id} = auth.uid()` }),
    pgPolicy("no_update_locked", { as: "restrictive", for: "update", to: ["public"], using: sql`${table.is_locked} = false`, withCheck: sql`${table.is_locked} = false` }),
]));

export const profiles = pgTable("profiles", {
    id: serial("id").primaryKey(),
    bio: varchar("bio"),
    website: varchar("website"),
    author_id: integer("author_id").references(() => authors.id, { onDelete: "set null" })
});

export const tags = pgTable("tags", {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull()
});

export const authorsRelations = drizzleRelations(authors, ({ one, many }) => ({
    profile: one(profiles, {
        fields: [authors.id],
        references: [profiles.author_id],
        relationName: "profile"
    }),
    posts: many(posts, { relationName: "posts" })
}));

export const postsRelations = drizzleRelations(posts, ({ one, many }) => ({
    author: one(authors, {
        fields: [posts.author_id],
        references: [authors.id],
        relationName: "author"
    }),
    tags: many(postsTags, { relationName: "tags" })
}));

export const postsTagsRelations = drizzleRelations(postsTags, ({ one, many }) => ({
    post_id: one(posts, {
        fields: [postsTags.post_id],
        references: [posts.id]
    }),
    tag_id: one(tags, {
        fields: [postsTags.tag_id],
        references: [tags.id]
    })
}));

export const profilesRelations = drizzleRelations(profiles, ({ one, many }) => ({
    author: one(authors, {
        fields: [profiles.author_id],
        references: [authors.id],
        relationName: "author"
    })
}));

export const tagsRelations = drizzleRelations(tags, ({ one, many }) => ({
    posts: many(posts, { relationName: "posts" })
}));

export const tables = { authors, posts, postsTags, privateNotes, profiles, tags };
export const enums = { postsStatus };
export const relations = { authorsRelations, postsRelations, postsTagsRelations, profilesRelations, tagsRelations };

