ALTER TABLE "posts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP SEQUENCE IF EXISTS "authors_id_seq" CASCADE;--> statement-breakpoint
ALTER TABLE "authors" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "authors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "private_notes" ALTER COLUMN "user_id" DROP NOT NULL;--> statement-breakpoint
CREATE POLICY "Enable read access for all users" ON "posts" AS PERMISSIVE FOR SELECT TO public USING ((true) AND (auth.roles() ~ 'public'));