version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:A%3FCl8L%5DpUHiO%3A%5COT@34.22.208.81:5432/maquindust-payload
      PORT: 3001
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
