/**
 * Generates the `client.js` file — a fetch-based HTTP client factory.
 *
 * Inspired by Supabase's createClient and Payload's local API patterns:
 * - Collection-namespaced CRUD methods (rebase.posts.find(), rebase.posts.findById())
 * - Supabase-style select with relation embedding
 * - PostgREST-style filter operators
 */

export function generateClient(): string {
    return `// ─── Auto-generated by Rebase SDK Generator ────────────────────────
// Do not edit manually. Re-run "rebase generate-sdk" to regenerate.
// ────────────────────────────────────────────────────────────────────

/**
 * @typedef {Object} RebaseClientConfig
 * @property {string} baseUrl - The base URL of the Rebase backend (e.g. "http://localhost:3001")
 * @property {string} [token] - JWT access token for authenticated requests
 * @property {string} [apiPath] - Base path for the REST API (default: "/api")
 * @property {typeof globalThis.fetch} [fetch] - Custom fetch implementation
 */

/**
 * @typedef {Object} FindParams
 * @property {number} [limit] - Maximum number of items to return (default: 20)
 * @property {number} [offset] - Number of items to skip
 * @property {number} [page] - Page number (1-indexed), alternative to offset
 * @property {Record<string, string>} [where] - PostgREST-style filter object.
 *   Keys are field names, values use "operator.value" format.
 *   Operators: eq, neq, gt, gte, lt, lte, in, nin, cs (array-contains), csa (array-contains-any)
 *   Examples:
 *     { status: "eq.published" }
 *     { age: "gte.18" }
 *     { role: "in.(admin,editor)" }
 * @property {string} [orderBy] - Sort order. Format: "field:direction".
 *   Examples: "created_at:desc", "name:asc"
 * @property {string[]} [include] - Relations to include in the response
 */

/**
 * @typedef {Object} FindResponse
 * @property {Array<Object>} data - Array of entities
 * @property {{ total: number, limit: number, offset: number, hasMore: boolean }} meta - Pagination metadata
 */

class RebaseApiError extends Error {
    /**
     * @param {number} status
     * @param {string} message
     * @param {string} [code]
     * @param {*} [details]
     */
    constructor(status, message, code, details) {
        super(message);
        this.name = "RebaseApiError";
        /** @type {number} */
        this.status = status;
        /** @type {string|undefined} */
        this.code = code;
        /** @type {*} */
        this.details = details;
    }
}

/**
 * Build query string from FindParams.
 * Converts the high-level params into the PostgREST-style query params
 * that the Rebase REST API expects.
 *
 * @param {FindParams} [params]
 * @returns {string}
 */
function buildQueryString(params) {
    if (!params) return "";
    const parts = [];

    if (params.limit != null) parts.push(\`limit=\${params.limit}\`);
    if (params.offset != null) parts.push(\`offset=\${params.offset}\`);
    if (params.page != null) parts.push(\`page=\${params.page}\`);

    if (params.orderBy) {
        parts.push(\`orderBy=\${encodeURIComponent(params.orderBy)}\`);
    }

    if (params.include && params.include.length > 0) {
        parts.push(\`include=\${encodeURIComponent(params.include.join(","))}\`);
    }

    // PostgREST-style filters: { status: "eq.published" } → ?status=eq.published
    if (params.where) {
        for (const [field, value] of Object.entries(params.where)) {
            parts.push(\`\${encodeURIComponent(field)}=\${encodeURIComponent(String(value))}\`);
        }
    }

    return parts.length > 0 ? "?" + parts.join("&") : "";
}

/**
 * Create a low-level HTTP transport for the Rebase REST API.
 *
 * @param {RebaseClientConfig} config
 * @returns {{ request: Function, setToken: Function }}
 */
function createTransport(config) {
    const fetchFn = config.fetch || globalThis.fetch;
    const apiPath = config.apiPath || "/api";
    let token = config.token;

    /**
     * @param {string} path
     * @param {RequestInit} [init]
     * @returns {Promise<*>}
     */
    async function request(path, init) {
        const url = config.baseUrl.replace(/\\/$/, "") + apiPath + path;
        const headers = {
            "Content-Type": "application/json",
            ...(token ? { Authorization: \`Bearer \${token}\` } : {}),
            ...(init?.headers || {}),
        };

        const res = await fetchFn(url, { ...init, headers });

        // 204 No Content (e.g. DELETE)
        if (res.status === 204) return undefined;

        const body = await res.json().catch(() => ({}));

        if (!res.ok) {
            throw new RebaseApiError(
                res.status,
                body?.error?.message || body?.message || res.statusText,
                body?.error?.code || body?.code,
                body?.error?.details || body?.details,
            );
        }

        return body;
    }

    return {
        request,
        /** Update the auth token at runtime (e.g. after refresh) */
        setToken(newToken) { token = newToken; },
    };
}

/**
 * Create a collection accessor with CRUD operations.
 * Each collection module calls this to create its namespace on the client.
 *
 * @param {{ request: Function }} transport
 * @param {string} slug - The collection slug used in the REST URL
 */
function createCollectionClient(transport, slug) {
    const basePath = \`/\${slug}\`;

    return {
        /**
         * Find multiple records with optional filtering, pagination, and sorting.
         * @param {FindParams} [params]
         * @returns {Promise<FindResponse>}
         */
        async find(params) {
            const qs = buildQueryString(params);
            return transport.request(basePath + qs, { method: "GET" });
        },

        /**
         * Find a single record by its ID.
         * @param {string|number} id
         * @returns {Promise<Object>}
         */
        async findById(id) {
            return transport.request(\`\${basePath}/\${encodeURIComponent(String(id))}\`, { method: "GET" });
        },

        /**
         * Create a new record.
         * @param {Object} data - The record data
         * @returns {Promise<Object>} The created record
         */
        async create(data) {
            return transport.request(basePath, {
                method: "POST",
                body: JSON.stringify(data),
            });
        },

        /**
         * Update an existing record by ID.
         * @param {string|number} id
         * @param {Object} data - The fields to update
         * @returns {Promise<Object>} The updated record
         */
        async update(id, data) {
            return transport.request(\`\${basePath}/\${encodeURIComponent(String(id))}\`, {
                method: "PUT",
                body: JSON.stringify(data),
            });
        },

        /**
         * Delete a record by ID.
         * @param {string|number} id
         * @returns {Promise<void>}
         */
        async delete(id) {
            return transport.request(\`\${basePath}/\${encodeURIComponent(String(id))}\`, {
                method: "DELETE",
            });
        },
    };
}

export { RebaseApiError, buildQueryString, createTransport, createCollectionClient };
`;
}
