import { EntityCollection, PostgresCollection, Property, Properties, MapProperty, ArrayProperty, RelationProperty, StringProperty, NumberProperty } from "@rebasepro/types";
import { resolveCollectionRelations } from "@rebasepro/common";
import { toPascalCase, toSafeIdentifier } from "./utils";

function propertyToTypeScriptType(prop: Property): string {
    switch (prop.type) {
        case "string": {
            const sp = prop as StringProperty;
            if (sp.enum) {
                const ids = Array.isArray(sp.enum)
                    ? sp.enum.map((e: any) => typeof e === "object" ? String(e.id) : String(e))
                    : Object.keys(sp.enum);
                return ids.map(v => `"${v}"`).join(" | ");
            }
            return "string";
        }
        case "number": {
            const np = prop as NumberProperty;
            if (np.enum) {
                const ids = Array.isArray(np.enum)
                    ? np.enum.map((e: any) => typeof e === "object" ? String(e.id) : String(e))
                    : Object.keys(np.enum);
                return ids.join(" | ");
            }
            return "number";
        }
        case "boolean":
            return "boolean";
        case "date":
            return "string"; // ISO 8601 string over the wire
        case "geopoint":
            return "{ latitude: number; longitude: number; }";
        case "reference":
            return "string | number";
        case "relation":
            return "string | number";
        case "map": {
            const mapProp = prop as MapProperty;
            if (mapProp.properties) {
                const inner = Object.entries(mapProp.properties)
                    .map(([k, v]) => `${toSafeIdentifier(k)}: ${propertyToTypeScriptType(v as Property)};`)
                    .join(" ");
                return `{ ${inner} }`;
            }
            return "Record<string, any>";
        }
        case "array": {
            const arrProp = prop as ArrayProperty;
            if (arrProp.of) {
                return `Array<${propertyToTypeScriptType(arrProp.of as Property)}>`;
            }
            return "Array<any>";
        }
        default:
            return "any";
    }
}

export function generateTypedefs(collections: EntityCollection[]): string {
    const lines: string[] = [
        `/**`,
        ` * This file was auto-generated by Rebase.`,
        ` * Do not make direct changes to the file.`,
        ` */`,
        ``,
        `export interface Database {`
    ];

    for (const collection of collections) {
        const typeName = toPascalCase(collection.slug);
        const properties = (collection.properties ?? {}) as Properties;

        // Resolve relations
        let resolvedRelations: Record<string, any> = {};
        try {
            resolvedRelations = resolveCollectionRelations(collection as PostgresCollection);
        } catch { /* ignore */ }

        lines.push(`  ${toSafeIdentifier(collection.slug)}: {`);
        
        // ── Row Type ──
        lines.push(`    Row: {`);
        const emittedKeys = new Set<string>();

        // 1. Direct properties
        for (const [key, rawProp] of Object.entries(properties)) {
            const prop = rawProp as Property;
            if (prop.type === "relation") continue; 

            const tsType = propertyToTypeScriptType(prop);
            const isRequired = prop.validation?.required;
            lines.push(`      ${toSafeIdentifier(key)}${isRequired ? "" : "?"}: ${tsType};`);
            emittedKeys.add(key);
        }
        
        // 2. FK columns from relations
        for (const [relKey, relation] of Object.entries(resolvedRelations)) {
            if (relation.direction === "owning" && relation.cardinality === "one" && relation.localKey) {
                const fkKey = relation.localKey;
                if (emittedKeys.has(fkKey)) continue;

                let fkType = "string | number";
                try {
                    const target = relation.target();
                    if (target.properties) {
                        const idProp = Object.entries(target.properties).find(([_, p]: [string, any]) => p.isId);
                        if (idProp) {
                            fkType = (idProp[1] as Property).type === "number" ? "number" : "string";
                        }
                    }
                } catch { /* ignore */ }

                const isRequired = relation.validation?.required;
                lines.push(`      ${toSafeIdentifier(fkKey)}${isRequired ? "" : "?"}: ${fkType};`);
                emittedKeys.add(fkKey);
            }
        }
        lines.push(`    };`);

        // ── Insert Type ──
        lines.push(`    Insert: {`);
        emittedKeys.clear();

        for (const [key, rawProp] of Object.entries(properties)) {
            const prop = rawProp as Property;
            if (prop.type === "relation") continue; 
            const tsType = propertyToTypeScriptType(prop);
            const isRequired = prop.validation?.required;
            const typedProp = prop as StringProperty | NumberProperty;
            const isAutoId = "isId" in prop && typedProp.isId && typedProp.isId !== "manual" && typedProp.isId !== true;
            const isOptional = !isRequired || isAutoId;
            lines.push(`      ${toSafeIdentifier(key)}${isOptional ? "?" : ""}: ${tsType};`);
            emittedKeys.add(key);
        }

        for (const [relKey, relation] of Object.entries(resolvedRelations)) {
            if (relation.direction === "owning" && relation.cardinality === "one" && relation.localKey) {
                const fkKey = relation.localKey;
                if (emittedKeys.has(fkKey)) continue;
                let fkType = "string | number";
                // simple fallback
                const isRequired = relation.validation?.required;
                lines.push(`      ${toSafeIdentifier(fkKey)}${isRequired ? "" : "?"}: ${fkType};`);
                emittedKeys.add(fkKey);
            }
        }
        lines.push(`    };`);

        // ── Update Type ──
        lines.push(`    Update: {`);
        emittedKeys.clear();
        for (const [key, rawProp] of Object.entries(properties)) {
            const prop = rawProp as Property;
            if (prop.type === "relation") continue; 
            const tsType = propertyToTypeScriptType(prop);
            lines.push(`      ${toSafeIdentifier(key)}?: ${tsType};`);
            emittedKeys.add(key);
        }
        for (const [relKey, relation] of Object.entries(resolvedRelations)) {
            if (relation.direction === "owning" && relation.cardinality === "one" && relation.localKey) {
                const fkKey = relation.localKey;
                if (emittedKeys.has(fkKey)) continue;
                lines.push(`      ${toSafeIdentifier(fkKey)}?: string | number;`);
                emittedKeys.add(fkKey);
            }
        }
        lines.push(`    };`);

        lines.push(`  };`);
    }

    lines.push(`}`);
    lines.push(``);

    return lines.join("\n");
}
