/**
 * Generates a per-collection JS module with typed CRUD operations.
 *
 * Each module exports a function that accepts the transport and returns
 * a collection client with jsdoc-typed find/findById/create/update/delete methods.
 *
 * Example output for "posts" collection:
 *
 *   import { createCollectionClient } from './client.js';
 *
 *   /** @typedef {Object} Posts ... * /
 *
 *   export function createPostsClient(transport) {
 *       return createCollectionClient(transport, "posts");
 *   }
 */

import { EntityCollection } from "@rebasepro/types";
import { toPascalCase, toCamelCase } from "./utils";
import { generateTypedefs } from "./generate-types";

export interface GeneratedCollectionModule {
    fileName: string;         // e.g. "posts.js"
    content: string;          // full file content
    slug: string;             // e.g. "posts"
    varName: string;          // e.g. "posts" (camelCase)
    factoryName: string;      // e.g. "createPostsClient"
    typeName: string;         // e.g. "Posts"
    relationNames: string[];  // e.g. ["author", "tags"]
}

export function generateCollectionModule(collection: EntityCollection): GeneratedCollectionModule {
    const slug = collection.slug;
    const typeName = toPascalCase(slug);
    const varName = toCamelCase(slug);
    const factoryName = `create${typeName}Client`;

    // Generate JSDoc typedefs for this collection
    const { entityTypedef, createTypedef, updateTypedef, relationNames } = generateTypedefs(collection);

    const relationDoc = relationNames.length > 0
        ? ` *   Available relations: ${relationNames.map(r => `"${r}"`).join(", ")}`
        : ` *   No relations available for this collection.`;

    const content = `// ─── Auto-generated by Rebase SDK Generator ────────────────────────
// Do not edit manually. Re-run "rebase generate-sdk" to regenerate.
// Collection: ${collection.name} (slug: ${slug})
// ────────────────────────────────────────────────────────────────────

import { createCollectionClient } from './client.js';

// ─── Type Definitions ──────────────────────────────────────────────

${entityTypedef}

${createTypedef}

${updateTypedef}

// ─── Collection Client ─────────────────────────────────────────────

/**
 * Create a typed client for the "${collection.name}" collection.
 *
 * @param {{ request: Function }} transport - The HTTP transport from createRebaseClient
 * @returns {{
 *   find: (params?: import('./client.js').FindParams) => Promise<import('./client.js').FindResponse & { data: ${typeName}[] }>,
 *   findById: (id: string | number) => Promise<${typeName}>,
 *   create: (data: ${typeName}CreateInput) => Promise<${typeName}>,
 *   update: (id: string | number, data: ${typeName}UpdateInput) => Promise<${typeName}>,
 *   delete: (id: string | number) => Promise<void>
 * }}
 *
 * Relations:
${relationDoc}
 */
export function ${factoryName}(transport) {
    return createCollectionClient(transport, "${slug}");
}
`;

    return {
        fileName: `${slug}.js`,
        content,
        slug,
        varName,
        factoryName,
        typeName,
        relationNames,
    };
}
