/**
 * Generates the SDK's index.js — the main entry point that creates a unified client
 * with all collection namespaces.
 *
 * Usage output:
 *   import { createRebaseClient } from './generated/sdk/index.js';
 *   const rebase = createRebaseClient({ baseUrl: 'http://localhost:3001', token: '...' });
 *   const { data } = await rebase.posts.find({ limit: 10 });
 */

import { GeneratedCollectionModule } from "./generate-collection-module";

export function generateIndex(modules: GeneratedCollectionModule[]): string {
    const imports = modules.map(m =>
        `import { ${m.factoryName} } from './${m.slug}.js';`
    ).join("\n");

    const clientProperties = modules.map(m =>
        `        /** @type {ReturnType<typeof ${m.factoryName}>} */\n        ${m.varName}: ${m.factoryName}(transport),`
    ).join("\n");

    const reExports = modules.map(m =>
        `export { ${m.factoryName} } from './${m.slug}.js';`
    ).join("\n");

    return `// ─── Auto-generated by Rebase SDK Generator ────────────────────────
// Do not edit manually. Re-run "rebase generate-sdk" to regenerate.
// ────────────────────────────────────────────────────────────────────

import { createTransport, RebaseApiError, buildQueryString } from './client.js';
${imports}

/**
 * Create a Rebase client with typed collection accessors.
 *
 * @param {import('./client.js').RebaseClientConfig} config
 * @returns {{
 *   ${modules.map(m => `${m.varName}: ReturnType<typeof ${m.factoryName}>`).join(",\n *   ")},
 *   setToken: (token: string) => void
 * }}
 *
 * @example
 * import { createRebaseClient } from './generated/sdk/index.js';
 *
 * const rebase = createRebaseClient({
 *     baseUrl: 'http://localhost:3001',
 *     token: 'eyJ...'
 * });
 *
 * // List with filtering
 * const { data, meta } = await rebase.posts.find({
 *     limit: 10,
 *     where: { status: 'eq.published' },
 *     orderBy: 'created_at:desc',
 * });
 *
 * // Get by ID
 * const post = await rebase.posts.findById(1);
 *
 * // Create
 * const newPost = await rebase.posts.create({ title: 'Hello', content: '...' });
 *
 * // Update
 * await rebase.posts.update(1, { title: 'Updated' });
 *
 * // Delete
 * await rebase.posts.delete(1);
 *
 * // Swap token after auth refresh
 * rebase.setToken('new-jwt-token');
 */
export function createRebaseClient(config) {
    const transport = createTransport(config);

    return {
${clientProperties}
        /** Update the auth token at runtime */
        setToken: transport.setToken,
    };
}

// Re-export individual collection clients for tree-shaking
${reExports}

// Re-export utilities
export { RebaseApiError, buildQueryString } from './client.js';
`;
}
