/**
 * Generates JSDoc @typedef blocks for each collection entity based on its properties.
 * Uses resolveCollectionRelations from @rebasepro/common to understand FK columns
 * and relation shapes, just like the Drizzle schema generator does.
 */

import { EntityCollection, Property, Properties, MapProperty, ArrayProperty, RelationProperty, StringProperty, NumberProperty } from "@rebasepro/types";
import { resolveCollectionRelations } from "@rebasepro/common";
import { toPascalCase } from "./utils";

// ─── Property → JS type mapping ────────────────────────────────────

/**
 * Map a Rebase property type to a JSDoc type string.
 */
function propertyToJsDocType(prop: Property, enumVals?: string[]): string {
    switch (prop.type) {
        case "string": {
            const sp = prop as StringProperty;
            if (sp.enum) {
                const ids = Array.isArray(sp.enum)
                    ? sp.enum.map((e: any) => typeof e === "object" ? String(e.id) : String(e))
                    : Object.keys(sp.enum);
                return ids.map(v => `"${v}"`).join(" | ");
            }
            return "string";
        }
        case "number": {
            const np = prop as NumberProperty;
            if (np.enum) {
                const ids = Array.isArray(np.enum)
                    ? np.enum.map((e: any) => typeof e === "object" ? String(e.id) : String(e))
                    : Object.keys(np.enum);
                return ids.join(" | ");
            }
            return "number";
        }
        case "boolean":
            return "boolean";
        case "date":
            return "string"; // ISO 8601 over the wire
        case "geopoint":
            return "{ latitude: number, longitude: number }";
        case "reference":
            return "string | number";
        case "relation":
            // SDK types for relation properties depend on cardinality — handled separately
            return "string | number";
        case "map": {
            const mapProp = prop as MapProperty;
            if (mapProp.properties) {
                const inner = Object.entries(mapProp.properties)
                    .map(([k, v]) => `${k}: ${propertyToJsDocType(v as Property)}`)
                    .join(", ");
                return `{ ${inner} }`;
            }
            return "Object";
        }
        case "array": {
            const arrProp = prop as ArrayProperty;
            if (arrProp.of) {
                return `Array<${propertyToJsDocType(arrProp.of as Property)}>`;
            }
            return "Array<*>";
        }
        default:
            return "*";
    }
}

// ─── Typedef generators ────────────────────────────────────────────

export interface TypedefResult {
    entityTypedef: string;
    createTypedef: string;
    updateTypedef: string;
    /** Available relation names for this collection (for jsdoc on include param) */
    relationNames: string[];
}

/**
 * Generate all JSDoc typedefs for a collection: Entity, CreateInput, UpdateInput.
 * Uses resolveCollectionRelations to understand FK columns generated by relations.
 */
export function generateTypedefs(collection: EntityCollection): TypedefResult {
    const typeName = toPascalCase(collection.slug);
    const properties = (collection.properties ?? {}) as Properties;

    // Resolve relations the same way the Drizzle schema generator does.
    let resolvedRelations: Record<string, any> = {};
    try {
        resolvedRelations = resolveCollectionRelations(collection);
    } catch {
        // If relations can't be resolved (e.g. circular or missing target), continue without them
    }

    // Collect relation names for the include param
    const relationNames = Object.keys(resolvedRelations);

    // ── Entity typedef (what comes back from the API) ──
    const entityLines: string[] = [`/**`, ` * @typedef {Object} ${typeName}`];
    const createLines: string[] = [`/**`, ` * @typedef {Object} ${typeName}CreateInput`];
    const updateLines: string[] = [`/**`, ` * @typedef {Object} ${typeName}UpdateInput`];

    // Track which property keys we've already emitted (to avoid duplication when
    // a relation property overlaps with an explicit column property)
    const emittedKeys = new Set<string>();

    // 1. Emit direct (non-relation) properties
    for (const [key, rawProp] of Object.entries(properties)) {
        const prop = rawProp as Property;
        if (prop.type === "relation") continue; // handled below

        const jsType = propertyToJsDocType(prop);
        const isRequired = prop.validation?.required;
        const isAutoId = "isId" in prop && (prop as any).isId && (prop as any).isId !== "manual" && (prop as any).isId !== true;

        // Entity type: all fields present
        entityLines.push(` * @property {${jsType}} ${isRequired ? key : `[${key}]`}`);

        // Create input: skip auto-generated IDs
        if (!isAutoId) {
            createLines.push(` * @property {${jsType}} ${isRequired ? key : `[${key}]`}`);
        }

        // Update input: everything optional
        updateLines.push(` * @property {${jsType}} [${key}]`);

        emittedKeys.add(key);
    }

    // 2. Emit FK columns from owning relations (these are actual DB columns)
    for (const [relKey, relation] of Object.entries(resolvedRelations)) {
        if (relation.direction === "owning" && relation.cardinality === "one" && relation.localKey) {
            const fkKey = relation.localKey;
            if (emittedKeys.has(fkKey)) continue; // Already emitted via properties

            // Determine FK type based on target's primary key
            let fkType = "string | number";
            try {
                const target = relation.target();
                if (target.properties) {
                    const idProp = Object.entries(target.properties).find(([_, p]: [string, any]) => p.isId);
                    if (idProp) {
                        fkType = (idProp[1] as Property).type === "number" ? "number" : "string";
                    }
                }
            } catch { /* keep generic type */ }

            const isRequired = relation.validation?.required;

            entityLines.push(` * @property {${fkType}} ${isRequired ? fkKey : `[${fkKey}]`} - FK to ${relKey}`);
            createLines.push(` * @property {${fkType}} ${isRequired ? fkKey : `[${fkKey}]`} - FK to ${relKey}`);
            updateLines.push(` * @property {${fkType}} [${fkKey}] - FK to ${relKey}`);

            emittedKeys.add(fkKey);
        }
    }

    entityLines.push(` */`);
    createLines.push(` */`);
    updateLines.push(` */`);

    return {
        entityTypedef: entityLines.join("\n"),
        createTypedef: createLines.join("\n"),
        updateTypedef: updateLines.join("\n"),
        relationNames,
    };
}
