/**
 * @rebasepro/sdk_generator
 *
 * Generates a typed JavaScript SDK from Rebase EntityCollection definitions.
 * The generated SDK provides a Supabase/Payload-style client for the REST API.
 */

export { generateClient } from "./generate-client";
export { generateTypedefs, type TypedefResult } from "./generate-types";
export { generateCollectionModule, type GeneratedCollectionModule } from "./generate-collection-module";
export { generateIndex } from "./generate-index";
export { toPascalCase, toCamelCase, toSafeIdentifier, indent } from "./utils";

import { EntityCollection } from "@rebasepro/types";
import { generateClient } from "./generate-client";
import { generateCollectionModule, GeneratedCollectionModule } from "./generate-collection-module";
import { generateIndex } from "./generate-index";

// ─── Public API ────────────────────────────────────────────────────

export interface GeneratedFile {
    /** Relative file path within the output directory */
    path: string;
    /** File content */
    content: string;
}

export interface GenerateSDKOptions {
    /**
     * Whether to include a README.md with usage examples.
     * @default true
     */
    includeReadme?: boolean;
}

/**
 * Generate all SDK files from a list of EntityCollection definitions.
 *
 * @param collections - The Rebase collections to generate the SDK for
 * @param options - Generation options
 * @returns Array of files to write to the output directory
 */
export function generateSDK(
    collections: EntityCollection[],
    options: GenerateSDKOptions = {},
): GeneratedFile[] {
    const { includeReadme = true } = options;
    const files: GeneratedFile[] = [];

    // 1. Generate the shared HTTP client
    files.push({
        path: "client.js",
        content: generateClient(),
    });

    // 2. Generate per-collection modules
    const modules: GeneratedCollectionModule[] = [];
    for (const collection of collections) {
        try {
            const mod = generateCollectionModule(collection);
            modules.push(mod);
            files.push({
                path: mod.fileName,
                content: mod.content,
            });
        } catch (err) {
            console.warn(`[sdk-generator] Skipping collection "${collection.slug}": ${(err as Error).message}`);
        }
    }

    // 3. Generate the unified index
    files.push({
        path: "index.js",
        content: generateIndex(modules),
    });

    // 4. Optional README
    if (includeReadme) {
        files.push({
            path: "README.md",
            content: generateReadme(modules),
        });
    }

    return files;
}

// ─── README generator ──────────────────────────────────────────────

function generateReadme(modules: GeneratedCollectionModule[]): string {
    const collectionList = modules.map(m =>
        `- **\`rebase.${m.varName}\`** — \`${m.typeName}\` (slug: \`${m.slug}\`)${m.relationNames.length > 0 ? ` | Relations: ${m.relationNames.join(", ")}` : ""}`
    ).join("\n");

    return `# Rebase SDK

> Auto-generated by \`rebase generate-sdk\`. Do not edit manually.

## Quick Start

\`\`\`js
import { createRebaseClient } from './index.js';

const rebase = createRebaseClient({
    baseUrl: 'http://localhost:3001',
    token: 'your-jwt-token',
});
\`\`\`

## Available Collections

${collectionList}

## CRUD Operations

\`\`\`js
// List with filters (PostgREST-style operators)
const { data, meta } = await rebase.posts.find({
    limit: 10,
    where: { status: 'eq.published' },
    orderBy: 'created_at:desc',
});

// Get single record
const post = await rebase.posts.findById(1);

// Create
const newPost = await rebase.posts.create({
    title: 'Hello World',
    content: 'My first post',
});

// Update
const updated = await rebase.posts.update(1, {
    title: 'Updated Title',
});

// Delete
await rebase.posts.delete(1);
\`\`\`

## Filtering

Use PostgREST-style operators in the \`where\` parameter:

| Operator | Meaning | Example |
|----------|---------|---------|
| \`eq\` | Equals | \`{ status: 'eq.published' }\` |
| \`neq\` | Not equals | \`{ status: 'neq.draft' }\` |
| \`gt\` | Greater than | \`{ age: 'gt.18' }\` |
| \`gte\` | Greater or equal | \`{ age: 'gte.18' }\` |
| \`lt\` | Less than | \`{ price: 'lt.100' }\` |
| \`lte\` | Less or equal | \`{ price: 'lte.100' }\` |
| \`in\` | In list | \`{ role: 'in.(admin,editor)' }\` |
| \`nin\` | Not in list | \`{ role: 'nin.(banned)' }\` |
| \`cs\` | Array contains | \`{ tags: 'cs.news' }\` |
| \`csa\` | Array contains any | \`{ tags: 'csa.(news,tech)' }\` |

## Authentication

\`\`\`js
// Set token at creation
const rebase = createRebaseClient({ baseUrl: '...', token: 'jwt-here' });

// Update token after auth refresh
rebase.setToken('new-jwt-token');
\`\`\`

## Error Handling

\`\`\`js
import { RebaseApiError } from './index.js';

try {
    await rebase.posts.findById(999);
} catch (err) {
    if (err instanceof RebaseApiError) {
        console.error(err.status, err.message, err.code);
    }
}
\`\`\`
`;
}
