import fs from "fs";
import path from "path";

import { fileURLToPath } from "url";
import { keyToIconComponent } from "../util/key_to_icon_component.ts";

/**
 * Regenerate `src/icons/generated_icons.ts` from the Material Symbols key list.
 *
 * This used to write one file per icon, each holding a full `forwardRef` body.
 * That cost 445KB in the bundle once the React Compiler gave every one of them
 * its own memo cache, so the bodies now collapse to a single shared factory in
 * `icons/create_icon.tsx` and this writes only the export list.
 *
 * The exported names are a published API — tenant bundles resolve them by name
 * out of the share scope — so a regeneration must only ever add names. If a key
 * change would drop or rename an existing export, keep the old export too.
 */
export function saveIconFiles(iconKeys: string[]) {
    const __dirname = path.dirname(fileURLToPath(import.meta.url));

    const generatedComponents = new Set<string>();
    const exportLines: string[] = [];

    iconKeys.forEach((key: string) => {
        if (!key) return;
        const componentName = keyToIconComponent(key);

        if (componentName === "Icon") {
            console.log("Skipping Icon component generation to avoid conflict");
            return;
        }

        if (generatedComponents.has(componentName.toLowerCase())) {
            console.log(`Skipping duplicate component ${componentName} for key ${key}`);
            return;
        }
        generatedComponents.add(componentName.toLowerCase());

        exportLines.push(`export const ${componentName} = /* @__PURE__ */ createIcon("${key}");`);
    });

    const contents = `/**
 * Generated by \`src/scripts/saveIconFiles.ts\` — do not edit by hand.
 *
 * One export per Material Symbols ligature. Every name here is part of the
 * published \`@firecms/ui\` surface and is resolved by name out of the share scope
 * by tenant bundles, so entries are only ever added.
 */
import { createIcon } from "./create_icon";

${exportLines.join("\n")}
`;

    const filePath = path.join(__dirname, "../icons/generated_icons.ts");
    console.log(`Saving ${exportLines.length} icon exports to ${filePath}`);
    fs.writeFileSync(filePath, contents);
}
