import { SvgIconProps } from "@mui/material/SvgIcon";
import { CMSType, DataType, PropertyOrBuilder } from "./properties";
import { FieldProps } from "./fields";

/**
 * This is the configuration object for the field component generated for a
 * property.
 * These configs are generated by default for the properties defined in your
 * collections' configuration, but you can define your own to be used
 */
export type FieldConfig<T extends CMSType = any> = {
    /**
     * Name of this field type.
     * This is not the name of the property.
     */
    name: string;

    /**
     * Data type related to this field.
     */
    dataType: DataType;

    /**
     * You can define a custom Field component to be used for this field.
     * Your custom Field is responsible for rendering the property value
     * and updating it when the user changes it.
     */
    Field?: React.ComponentType<FieldProps<T>>;

    /**
     * You can define a default config for the property.
     * Whenever this field is used, this property or builder will be used as
     * the base values for the resulting property.
     * Any props that are defined in the property will override the
     * ones specified in `baseProperty`.
     * You can also use a builder function to generate the base property.
     */
    defaultProperty?: PropertyOrBuilder<T>;

    Icon?: React.ComponentType<SvgIconProps>;

    /**
     * CSS color, used only in some plugins like the field selector.
     * e.g. "#2d7ff9"
     */
    color?: string;

    /**
     * Description of this field type.
     */
    description?: string;

}

export type FieldConfigId =
    "text_field" |
    "multiline" |
    "markdown" |
    "url" |
    "email" |
    "select" |
    "multi_select" |
    "number_input" |
    "number_select" |
    "multi_number_select" |
    "file_upload" |
    "multi_file_upload" |
    "group" |
    "key_value" |
    "reference" |
    "multi_references" |
    "switch" |
    "date_time" |
    "repeat" |
    "custom_array" |
    "block";
