module.exports = {
    docsSidebar: [
        {
            type: 'doc',
            label: 'Introduction',
            id: 'intro'
        },
        'quickstart',
        {
            type: 'category',
            label: 'Collections',
            items: [
                'collections/collections',
                'collections/saving_callbacks',
                'collections/permissions',
                'collections/exporting_data',
                {
                    type: 'category',
                    label: 'Entities',
                    items: [
                        {
                            type: 'category',
                            label: 'Properties',
                            items: [
                                'collections/config/properties/properties_intro',
                                'collections/config/properties/string',
                                'collections/config/properties/number',
                                'collections/config/properties/boolean',
                                'collections/config/properties/reference',
                                'collections/config/properties/timestamp',
                                'collections/config/properties/array',
                                'collections/config/properties/map',
                                'collections/config/properties/geopoint'
                            ]
                        },
                        'collections/config/conditional_fields',
                        'collections/config/custom_fields',
                        'collections/config/custom_previews',
                        'collections/config/custom_schema_views',
                    ]
                }
            ]
        },
        'navigation',
        {
            type: 'category',
            label: 'Provided hooks',
            items: [
                'hooks/use_auth_controller',
                'hooks/use_side_entity_controller',
                'hooks/use_snackbar_controller',
                'hooks/use_firecms_context',
                'hooks/use_data_source',
                'hooks/use_storage_source',
            ]
        },
        {
            type: 'category',
            label: 'Firebase CMS app',
            items: [
                'firebase_cms_app',
                'firebase_setup',
                'deployment',
            ]
        },
        {
            type: 'category',
            label: 'Recipes',
            items: [
                // 'recipes/recipes_index',
                'recipes/building_a_blog',
            ]
        },
        'custom_cms_app',
        'migrating_from_alpha_versions',
        'changelog'
    ],

    apiSidebar: [{
        type: 'autogenerated',
        dirName: 'api'
    }]
}

