export const datatalkTranslationsEn = {
    datatalk_auto_run_code_tooltip: "Run snippets of code generated by DataTalk automatically.\nCaution: This can be risky since scripts may modify your data in ways you don't expect",
    datatalk_auto_run_code: "Run code automatically",
    datatalk_type_message: "Type your message...",
    datatalk_session_started: "DataTalk session started",
    datatalk_welcome: "Welcome to DATATALK",
    datatalk_subtitle: "DataTalk is a conversational interface to your data. You can ask questions, run commands and explore your data in a natural way.",
    datatalk_examples_title: "Here are some examples of things you can ask:",
    datatalk_sample_1: "What can you do?",
    datatalk_sample_2: "What collections are available?",
    datatalk_sample_3: "Show me all products under 50 euros",
    datatalk_sample_4: "Create a new book with data for El Quijote.",
    datatalk_sample_5: "Show me the 10 cars with the most horsepower.",
    datatalk_note_generic: "Note that these sample prompts are generic and may not work with your specific data.",
    datatalk_note_dependencies: "You can't add additional imports or dependencies to the code snippets.",
    datatalk_error_processing_command: "There was an error processing your command: {{error}}",
    datatalk_new_chat: "New Chat",
    datatalk_no_conversations_yet: "No conversations yet",
    datatalk_new_conversation: "New conversation",
    datatalk_regenerate: "Regenerate",
    datatalk_copy: "Copy",
    datatalk_bad_response: "Bad response",
    datatalk_what_was_wrong: "What was wrong with the response?",
    datatalk_not_helpful: "Not helpful",
    datatalk_not_factually_correct: "Not factually correct",
    datatalk_incorrect_code: "Incorrect code",
    datatalk_unsafe_or_problematic: "Unsafe or problematic",
    datatalk_other: "Other",
    datatalk_feedback_details: "Feel free to add specific details"
};

declare module "@firecms/core" {
    export interface FireCMSTranslations {
        datatalk_auto_run_code_tooltip?: string;
        datatalk_auto_run_code?: string;
        datatalk_type_message?: string;
        datatalk_session_started?: string;
        datatalk_welcome?: string;
        datatalk_subtitle?: string;
        datatalk_examples_title?: string;
        datatalk_sample_1?: string;
        datatalk_sample_2?: string;
        datatalk_sample_3?: string;
        datatalk_sample_4?: string;
        datatalk_sample_5?: string;
        datatalk_note_generic?: string;
        datatalk_note_dependencies?: string;
        datatalk_error_processing_command?: string;
        datatalk_new_chat?: string;
        datatalk_no_conversations_yet?: string;
        datatalk_new_conversation?: string;
        datatalk_regenerate?: string;
        datatalk_copy?: string;
        datatalk_bad_response?: string;
        datatalk_what_was_wrong?: string;
        datatalk_not_helpful?: string;
        datatalk_not_factually_correct?: string;
        datatalk_incorrect_code?: string;
        datatalk_unsafe_or_problematic?: string;
        datatalk_other?: string;
        datatalk_feedback_details?: string;
    }
}
